// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;
using TTRPGHelper.Api.Infrastructure.Database;

#nullable disable

namespace TTRPGHelper.Api.Infrastructure.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TTRPGHelper.Api.Modules.Conversations.Entities.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("TTRPGHelper.Api.Modules.Conversations.Entities.ConversationMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<List<Guid>>("ReferencedChunkIds")
                        .HasColumnType("uuid[]");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.ToTable("ConversationMessages");
                });

            modelBuilder.Entity("TTRPGHelper.Api.Modules.KnowledgeBase.Entities.EntityChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentHash")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(768)");

                    b.Property<string>("EmbeddingModel")
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("ReferencedEntityNames")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("SectionHeading")
                        .HasColumnType("text");

                    b.Property<Guid>("WorldEntityId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Embedding");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Embedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Embedding"), new[] { "vector_cosine_ops" });

                    b.HasIndex("WorldEntityId");

                    b.ToTable("EntityChunks");
                });

            modelBuilder.Entity("TTRPGHelper.Api.Modules.KnowledgeBase.Entities.EntityRelationship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("FromEntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("RelationshipType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ToEntityId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FromEntityId");

                    b.HasIndex("ToEntityId");

                    b.ToTable("EntityRelationships");
                });

            modelBuilder.Entity("TTRPGHelper.Api.Modules.KnowledgeBase.Entities.WorldEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Dictionary<string, string>>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EntityType");

                    b.HasIndex("Name");

                    b.ToTable("WorldEntities");
                });

            modelBuilder.Entity("TTRPGHelper.Api.Modules.Conversations.Entities.ConversationMessage", b =>
                {
                    b.HasOne("TTRPGHelper.Api.Modules.Conversations.Entities.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("TTRPGHelper.Api.Modules.KnowledgeBase.Entities.EntityChunk", b =>
                {
                    b.HasOne("TTRPGHelper.Api.Modules.KnowledgeBase.Entities.WorldEntity", "WorldEntity")
                        .WithMany("Chunks")
                        .HasForeignKey("WorldEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorldEntity");
                });

            modelBuilder.Entity("TTRPGHelper.Api.Modules.KnowledgeBase.Entities.EntityRelationship", b =>
                {
                    b.HasOne("TTRPGHelper.Api.Modules.KnowledgeBase.Entities.WorldEntity", "FromEntity")
                        .WithMany("RelationshipsFrom")
                        .HasForeignKey("FromEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TTRPGHelper.Api.Modules.KnowledgeBase.Entities.WorldEntity", "ToEntity")
                        .WithMany("RelationshipsTo")
                        .HasForeignKey("ToEntityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromEntity");

                    b.Navigation("ToEntity");
                });

            modelBuilder.Entity("TTRPGHelper.Api.Modules.Conversations.Entities.Conversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("TTRPGHelper.Api.Modules.KnowledgeBase.Entities.WorldEntity", b =>
                {
                    b.Navigation("Chunks");

                    b.Navigation("RelationshipsFrom");

                    b.Navigation("RelationshipsTo");
                });
#pragma warning restore 612, 618
        }
    }
}
